graph LR

  subgraph Master
    A(Master)
    A --> |"Create Feature Branch"| B(Feature Branch)
  end

  subgraph Feature
    B --> |"Implement Feature"| C(Feature Changes)
    C --> |"Commit Changes"| D(Commit)
    D --> |"Push to Remote"| E
  end

  subgraph Review
    E(Feature Branch)
    E --> |"Create Pull Request"| F(Pull Request)
    F --> |"Review Code"| G
    G --> |"Merge to Master"| H
  end

  subgraph Deploy
    H --> |"Deploy to Production"| I(Production)
  end
